"""
Глава 4. Вычислительный эксперимент по анализу транзакций игорной платформы.

Скрипт формирует модельный анонимизированный набор транзакций, строит признаки,
обучает модели машинного обучения, подбирает порог на валидационной выборке,
оценивает качество на тестовой выборке, рассчитывает экономические и очередные
показатели, а также сохраняет таблицы и графики.

Используются: pandas, numpy, scikit-learn, matplotlib.
Опционально используются imbalanced-learn и SHAP, если они установлены.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    fbeta_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.inspection import permutation_importance

RANDOM_STATE = 777
BASE_DIR = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
OUT_DIR = BASE_DIR / "chapter4_artifacts"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1 / (1 + np.exp(-x))


def generate_transactions(n: int = 12000, seed: int = RANDOM_STATE) -> pd.DataFrame:
    """Генерация модельных обезличенных транзакций с нелинейными и скрытыми паттернами."""
    rng = np.random.default_rng(seed)
    start = pd.Timestamp("2026-01-01")
    days = rng.integers(0, 90, size=n)
    seconds = rng.integers(0, 24 * 3600, size=n)
    timestamps = start + pd.to_timedelta(days, unit="D") + pd.to_timedelta(seconds, unit="s")
    timestamps = pd.Series(timestamps).sort_values().reset_index(drop=True)

    player_count = 1650
    player_ids = rng.integers(1, player_count + 1, size=n)
    player_hash = [f"plr_{x:05d}" for x in player_ids]
    latent_player_risk = rng.beta(a=1.4, b=8.5, size=player_count + 1)
    hidden_risk = latent_player_risk[player_ids]

    channel = rng.choice(["card", "e_wallet", "bank_transfer", "crypto_pvt"], size=n, p=[0.53, 0.21, 0.16, 0.10])
    operation_type = rng.choice(["deposit", "withdrawal", "refund"], size=n, p=[0.72, 0.22, 0.06])

    base_amount = rng.lognormal(mean=4.22, sigma=0.98, size=n)
    multiplier = np.where(operation_type == "withdrawal", 1.7, 1.0)
    multiplier *= np.where(channel == "crypto_pvt", 1.35, 1.0)
    amount_byn = np.clip(base_amount * multiplier, 10, 8500).round(2)

    hour = timestamps.dt.hour.to_numpy()
    day_of_week = timestamps.dt.dayofweek.to_numpy()
    is_weekend = (day_of_week >= 5).astype(int)
    is_night = ((hour < 6) | (hour >= 23)).astype(int)
    is_crypto = (channel == "crypto_pvt").astype(int)
    is_withdrawal = (operation_type == "withdrawal").astype(int)
    is_refund = (operation_type == "refund").astype(int)

    daily_tx_count = rng.poisson(lam=2.0 + 1.1 * is_weekend + 0.7 * is_crypto + 0.9 * hidden_risk, size=n) + 1
    previous_failed_cnt = rng.poisson(lam=0.14 + 0.36 * is_crypto + 0.25 * is_night + 0.8 * hidden_risk, size=n)
    account_age_days = rng.gamma(shape=2.8, scale=53, size=n).astype(int) + 1
    is_new_player = (account_age_days < 14).astype(int)
    kyc_score = np.clip(
        rng.normal(loc=0.86, scale=0.13, size=n) - 0.10 * is_new_player - 0.06 * is_crypto - 0.18 * hidden_risk,
        0.20,
        1.0,
    )

    # Latency is observable, but includes hidden operational shocks and bursts.
    burst_day = np.isin(days, rng.choice(np.arange(90), size=8, replace=False)).astype(int)
    latency_sec = (
        rng.gamma(shape=2.3, scale=28, size=n)
        + np.where(channel == "bank_transfer", 105, 0)
        + np.where(channel == "crypto_pvt", 175, 0)
        + np.where(previous_failed_cnt > 1, 80, 0)
        + np.where(is_withdrawal == 1, 58, 0)
        + np.where(burst_day == 1, rng.gamma(2.0, 55, n), 0)
    )
    latency_sec = np.clip(latency_sec, 5, 2800).round(0).astype(int)

    commission_rate = np.select(
        [channel == "card", channel == "e_wallet", channel == "bank_transfer", channel == "crypto_pvt"],
        [0.027, 0.018, 0.012, 0.0045],
        default=0.02,
    )
    commission_byn = (amount_byn * commission_rate).round(2)

    # Target label is generated by a noisy nonlinear mechanism. Several latent components are intentionally not in X.
    amount_high = (amount_byn > np.quantile(amount_byn, 0.86)).astype(int)
    amount_extreme = (amount_byn > np.quantile(amount_byn, 0.96)).astype(int)
    velocity_flag = ((daily_tx_count >= 6) & (previous_failed_cnt >= 1)).astype(int)
    crypto_withdrawal = ((is_crypto == 1) & (is_withdrawal == 1)).astype(int)
    night_new_player = ((is_night == 1) & (is_new_player == 1)).astype(int)
    low_kyc_large = ((kyc_score < 0.68) & (amount_byn > 900)).astype(int)
    hidden_cluster = ((hidden_risk > 0.24) & ((is_crypto == 1) | (is_refund == 1))).astype(int)
    operational_shock = ((latency_sec > 430) & (burst_day == 1)).astype(int)

    nonlinear_score = (
        0.55 * amount_high
        + 0.85 * amount_extreme
        + 1.20 * velocity_flag
        + 1.05 * crypto_withdrawal
        + 0.90 * night_new_player
        + 1.10 * low_kyc_large
        + 1.35 * hidden_cluster
        + 0.70 * operational_shock
        + 0.65 * is_refund
        + 0.45 * is_crypto
        + 0.35 * is_night
        + 0.18 * np.log1p(amount_byn)
        - 1.65 * kyc_score
        + rng.normal(0, 0.95, n)
    )
    risk_probability = sigmoid(-3.00 + nonlinear_score)
    manual_review = rng.binomial(1, risk_probability)

    status = np.where(manual_review == 1, "manual_review", "confirmed")
    technical_decline = (rng.random(n) < (0.022 + 0.025 * (channel == "bank_transfer") + 0.015 * burst_day)) & (manual_review == 0)
    status = np.where(technical_decline, "declined", status)

    df = pd.DataFrame(
        {
            "transaction_id": [f"tx_{i + 1:06d}" for i in range(n)],
            "player_hash": player_hash,
            "timestamp": timestamps,
            "channel": channel,
            "operation_type": operation_type,
            "amount_byn": amount_byn,
            "hour": hour,
            "day_of_week": day_of_week,
            "is_weekend": is_weekend,
            "is_night": is_night,
            "is_crypto": is_crypto,
            "account_age_days": account_age_days,
            "is_new_player": is_new_player,
            "kyc_score": np.round(kyc_score, 3),
            "daily_tx_count": daily_tx_count,
            "previous_failed_cnt": previous_failed_cnt,
            "latency_sec": latency_sec,
            "commission_rate": commission_rate,
            "commission_byn": commission_byn,
            "status": status,
            "manual_review": manual_review,
        }
    )
    df["date"] = df["timestamp"].dt.date.astype(str)
    return df


def prepare_xy(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series, List[str], List[str]]:
    features = [
        "channel",
        "operation_type",
        "amount_byn",
        "hour",
        "day_of_week",
        "is_weekend",
        "is_night",
        "is_crypto",
        "account_age_days",
        "is_new_player",
        "kyc_score",
        "daily_tx_count",
        "previous_failed_cnt",
        "latency_sec",
        "commission_rate",
    ]
    X = df[features]
    y = df["manual_review"]
    categorical = ["channel", "operation_type"]
    numeric = [x for x in features if x not in categorical]
    return X, y, categorical, numeric


def chronological_split(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    df_sorted = df.sort_values("timestamp").reset_index(drop=True)
    n = len(df_sorted)
    cut_train = int(n * 0.60)
    cut_val = int(n * 0.80)
    return df_sorted.iloc[:cut_train].copy(), df_sorted.iloc[cut_train:cut_val].copy(), df_sorted.iloc[cut_val:].copy()


def build_preprocessor(categorical: List[str], numeric: List[str]) -> ColumnTransformer:
    return ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
            ("num", StandardScaler(), numeric),
        ]
    )


def find_best_threshold(y_true: pd.Series, proba: np.ndarray, beta: float = 2.0) -> Dict[str, float]:
    thresholds = np.linspace(0.05, 0.95, 181)
    rows = []
    for thr in thresholds:
        pred = (proba >= thr).astype(int)
        rows.append(
            {
                "threshold": thr,
                "precision": precision_score(y_true, pred, zero_division=0),
                "recall": recall_score(y_true, pred, zero_division=0),
                "f1": f1_score(y_true, pred, zero_division=0),
                "f2": fbeta_score(y_true, pred, beta=beta, zero_division=0),
                "review_count": int(pred.sum()),
            }
        )
    table = pd.DataFrame(rows)
    best = table.loc[table["f2"].idxmax()].to_dict()
    return {k: float(v) for k, v in best.items()}


def evaluate_on_test(name: str, proba: np.ndarray, y_test: pd.Series, threshold: float) -> Dict[str, float]:
    pred = (proba >= threshold).astype(int)
    return {
        "model": name,
        "threshold_from_validation": round(threshold, 3),
        "roc_auc": round(roc_auc_score(y_test, proba), 3),
        "pr_auc": round(average_precision_score(y_test, proba), 3),
        "accuracy": round(accuracy_score(y_test, pred), 3),
        "precision": round(precision_score(y_test, pred, zero_division=0), 3),
        "recall": round(recall_score(y_test, pred, zero_division=0), 3),
        "f1": round(f1_score(y_test, pred, zero_division=0), 3),
        "f2": round(fbeta_score(y_test, pred, beta=2, zero_division=0), 3),
        "review_count": int(pred.sum()),
    }


def time_series_cv_scores(pipe: Pipeline, X_train: pd.DataFrame, y_train: pd.Series, name: str) -> Dict[str, float]:
    """Small TimeSeriesSplit check without heavy hyperparameter search."""
    rows = []
    tscv = TimeSeriesSplit(n_splits=3)
    for fold, (tr, va) in enumerate(tscv.split(X_train), start=1):
        model = pipe
        model.fit(X_train.iloc[tr], y_train.iloc[tr])
        proba = model.predict_proba(X_train.iloc[va])[:, 1]
        pred = (proba >= 0.5).astype(int)
        rows.append({
            "model": name,
            "fold": fold,
            "roc_auc": roc_auc_score(y_train.iloc[va], proba),
            "f1": f1_score(y_train.iloc[va], pred, zero_division=0),
            "f2": fbeta_score(y_train.iloc[va], pred, beta=2, zero_division=0),
        })
    df = pd.DataFrame(rows)
    return {
        "model": name,
        "cv_roc_auc_mean": df["roc_auc"].mean(),
        "cv_f1_mean": df["f1"].mean(),
        "cv_f2_mean": df["f2"].mean(),
    }


def train_models(df: pd.DataFrame) -> Dict[str, object]:
    train_df, val_df, test_df = chronological_split(df)
    X_train, y_train, categorical, numeric = prepare_xy(train_df)
    X_val, y_val, _, _ = prepare_xy(val_df)
    X_test, y_test, _, _ = prepare_xy(test_df)
    preprocessor = build_preprocessor(categorical, numeric)

    models: Dict[str, Pipeline] = {
        "LogisticRegression": Pipeline([("prep", preprocessor), ("clf", LogisticRegression(max_iter=1200, class_weight="balanced", random_state=RANDOM_STATE))]),
        "RandomForest": Pipeline([("prep", preprocessor), ("clf", RandomForestClassifier(n_estimators=90, max_depth=10, min_samples_leaf=6, class_weight="balanced", random_state=RANDOM_STATE, n_jobs=1))]),
        "GradientBoosting": Pipeline([("prep", preprocessor), ("clf", GradientBoostingClassifier(n_estimators=100, learning_rate=0.06, max_depth=2, random_state=RANDOM_STATE))]),
    }
    try:
        from imblearn.pipeline import Pipeline as ImbPipeline
        from imblearn.over_sampling import SMOTE
        models["LogisticRegression_SMOTE"] = ImbPipeline([("prep", preprocessor), ("smote", SMOTE(random_state=RANDOM_STATE, k_neighbors=5)), ("clf", LogisticRegression(max_iter=1200, random_state=RANDOM_STATE))])
    except Exception:
        pass

    cv_rows = []
    metrics_rows = []
    validation_rows = []
    fitted: Dict[str, Pipeline] = {}
    thresholds: Dict[str, float] = {}
    for name, pipe in models.items():
        cv_rows.append(time_series_cv_scores(pipe, X_train, y_train, name))
        pipe.fit(X_train, y_train)
        fitted[name] = pipe
        val_proba = pipe.predict_proba(X_val)[:, 1]
        best = find_best_threshold(y_val, val_proba, beta=2)
        thresholds[name] = best["threshold"]
        best["model"] = name
        validation_rows.append(best)
        test_proba = pipe.predict_proba(X_test)[:, 1]
        metrics_rows.append(evaluate_on_test(name, test_proba, y_test, thresholds[name]))

    cv_df = pd.DataFrame(cv_rows).sort_values("cv_f2_mean", ascending=False)
    metrics_df = pd.DataFrame(metrics_rows).sort_values(["f2", "roc_auc"], ascending=False)
    val_thresholds_df = pd.DataFrame(validation_rows).sort_values(["f2"], ascending=False)
    cv_df.to_csv(OUT_DIR / "timeseries_cv_scores.csv", index=False)
    metrics_df.to_csv(OUT_DIR / "model_metrics.csv", index=False)
    val_thresholds_df.to_csv(OUT_DIR / "validation_thresholds.csv", index=False)

    best_name = metrics_df.iloc[0]["model"]
    best_model = fitted[best_name]
    best_threshold = thresholds[best_name]
    best_proba = best_model.predict_proba(X_test)[:, 1]
    best_pred = (best_proba >= best_threshold).astype(int)

    return {
        "train_df": train_df,
        "val_df": val_df,
        "test_df": test_df,
        "X_train": X_train,
        "y_train": y_train,
        "X_val": X_val,
        "y_val": y_val,
        "X_test": X_test,
        "y_test": y_test,
        "models": fitted,
        "thresholds": thresholds,
        "cv_df": cv_df,
        "metrics_df": metrics_df,
        "validation_thresholds_df": val_thresholds_df,
        "best_name": best_name,
        "best_model": best_model,
        "best_threshold": best_threshold,
        "best_proba": best_proba,
        "best_pred": best_pred,
        "categorical": categorical,
        "numeric": numeric,
    }


def plot_channel_distribution(df: pd.DataFrame) -> None:
    counts = df["channel"].value_counts().sort_index()
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.bar(counts.index, counts.values)
    ax.set_title("Распределение транзакций по платёжным каналам")
    ax.set_xlabel("Платёжный канал")
    ax.set_ylabel("Количество транзакций")
    ax.tick_params(axis="x", rotation=20)
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_1_channel_distribution.png", dpi=220)
    plt.close(fig)


def plot_roc(y_test: pd.Series, proba: np.ndarray) -> None:
    fpr, tpr, _ = roc_curve(y_test, proba)
    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.plot(fpr, tpr, label=f"ROC-AUC = {roc_auc_score(y_test, proba):.3f}")
    ax.plot([0, 1], [0, 1], linestyle="--")
    ax.set_title("ROC-кривая лучшей модели")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.legend(loc="lower right")
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_2_roc_curve.png", dpi=220)
    plt.close(fig)


def plot_confusion(y_test: pd.Series, pred: np.ndarray) -> None:
    cm = confusion_matrix(y_test, pred)
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    im = ax.imshow(cm)
    ax.set_title("Матрица ошибок")
    ax.set_xlabel("Прогноз")
    ax.set_ylabel("Факт")
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
    ax.set_xticklabels(["обычная", "проверка"])
    ax.set_yticklabels(["обычная", "проверка"])
    for i in range(2):
        for j in range(2):
            ax.text(j, i, str(cm[i, j]), ha="center", va="center")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_3_confusion_matrix.png", dpi=220)
    plt.close(fig)


def threshold_sensitivity(y_test: pd.Series, proba: np.ndarray) -> pd.DataFrame:
    thresholds = [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80]
    rows = []
    for thr in thresholds:
        pred = (proba >= thr).astype(int)
        rows.append({
            "threshold": thr,
            "precision": precision_score(y_test, pred, zero_division=0),
            "recall": recall_score(y_test, pred, zero_division=0),
            "f1": f1_score(y_test, pred, zero_division=0),
            "f2": fbeta_score(y_test, pred, beta=2, zero_division=0),
            "review_count": int(pred.sum()),
        })
    out = pd.DataFrame(rows)
    out.to_csv(OUT_DIR / "threshold_sensitivity.csv", index=False)
    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    ax.plot(out["threshold"], out["precision"], marker="o", label="precision")
    ax.plot(out["threshold"], out["recall"], marker="o", label="recall")
    ax.plot(out["threshold"], out["f1"], marker="o", label="F1")
    ax.plot(out["threshold"], out["f2"], marker="o", label="F2")
    ax.set_title("Изменение метрик при разных порогах")
    ax.set_xlabel("Порог классификации")
    ax.set_ylabel("Значение метрики")
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_4_threshold_sensitivity.png", dpi=220)
    plt.close(fig)
    return out


def erlang_c(lambda_rate: float, mu: float, servers: int) -> Tuple[float, float, float, float]:
    """Return rho, P(wait), Wq hours, Lq for M/M/c. If unstable, return infinities."""
    if lambda_rate <= 0:
        return 0.0, 0.0, 0.0, 0.0
    a = lambda_rate / mu
    rho = lambda_rate / (servers * mu)
    if rho >= 1:
        return rho, 1.0, float("inf"), float("inf")
    denom = sum((a ** n) / math.factorial(n) for n in range(servers)) + (a ** servers) / (math.factorial(servers) * (1 - rho))
    p0 = 1 / denom
    p_wait = (a ** servers) / (math.factorial(servers) * (1 - rho)) * p0
    wq = p_wait / (servers * mu - lambda_rate)
    lq = lambda_rate * wq
    return rho, p_wait, wq, lq


def queue_analysis(sensitivity_df: pd.DataFrame, test_df: pd.DataFrame) -> pd.DataFrame:
    # test period length in days
    days = pd.to_datetime(test_df["date"]).nunique()
    service_time_min = 6.0
    mu = 60.0 / service_time_min
    peak_multiplier = 3.0
    rows = []
    for _, row in sensitivity_df.iterrows():
        daily_reviews = row["review_count"] / max(days, 1)
        lambda_hour = daily_reviews / 24.0 * peak_multiplier
        for c in [1, 2]:
            rho, p_wait, wq_h, lq = erlang_c(lambda_hour, mu, c)
            rows.append({
                "threshold": row["threshold"],
                "servers": c,
                "lambda_peak_hour": lambda_hour,
                "rho": rho,
                "p_wait": p_wait,
                "wq_minutes": wq_h * 60 if math.isfinite(wq_h) else np.inf,
                "lq": lq,
            })
    out = pd.DataFrame(rows)
    out.to_csv(OUT_DIR / "queue_analysis.csv", index=False)
    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    for c, sub in out.groupby("servers"):
        ax.plot(sub["threshold"], sub["wq_minutes"], marker="o", label=f"{c} оператор(а)")
    ax.set_title("Оценка ожидания ручной проверки по модели M/M/c")
    ax.set_xlabel("Порог классификации")
    ax.set_ylabel("Среднее ожидание в очереди, мин")
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_7_queue_waiting.png", dpi=220)
    plt.close(fig)
    return out


def cost_threshold_analysis(y_test: pd.Series, proba: np.ndarray) -> pd.DataFrame:
    c_fp = 4.0      # cost of unnecessary manual review, BYN
    c_fn = 250.0    # expected cost of missed high-risk transaction, BYN
    thresholds = np.linspace(0.10, 0.90, 17)
    rows = []
    for thr in thresholds:
        pred = (proba >= thr).astype(int)
        cm = confusion_matrix(y_test, pred)
        tn, fp, fn, tp = cm.ravel()
        total_cost = fp * c_fp + fn * c_fn
        rows.append({
            "threshold": round(float(thr), 2),
            "fp": int(fp),
            "fn": int(fn),
            "manual_review": int(pred.sum()),
            "cost_byn": round(total_cost, 2),
        })
    out = pd.DataFrame(rows)
    out.to_csv(OUT_DIR / "cost_threshold.csv", index=False)
    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    ax.plot(out["threshold"], out["cost_byn"], marker="o")
    best = out.loc[out["cost_byn"].idxmin()]
    ax.scatter([best["threshold"]], [best["cost_byn"]], s=80, zorder=4)
    ax.set_title("Суммарные издержки при разных порогах")
    ax.set_xlabel("Порог классификации")
    ax.set_ylabel("Издержки на тестовом периоде, BYN")
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_8_cost_threshold.png", dpi=220)
    plt.close(fig)
    return out


def train_daily_forecast(df: pd.DataFrame) -> Dict[str, object]:
    daily = df.groupby("date").agg(
        tx_count=("transaction_id", "count"),
        total_amount=("amount_byn", "sum"),
        avg_amount=("amount_byn", "mean"),
        avg_latency=("latency_sec", "mean"),
        crypto_share=("is_crypto", "mean"),
        manual_share=("manual_review", "mean"),
    ).reset_index()
    daily["date_dt"] = pd.to_datetime(daily["date"])
    daily["day_of_week"] = daily["date_dt"].dt.dayofweek
    daily["is_weekend"] = (daily["day_of_week"] >= 5).astype(int)
    for lag in [1, 2, 3, 7]:
        daily[f"lag_{lag}"] = daily["tx_count"].shift(lag)
    daily = daily.dropna().reset_index(drop=True)

    features = ["total_amount", "avg_amount", "avg_latency", "crypto_share", "manual_share", "day_of_week", "is_weekend", "lag_1", "lag_2", "lag_3", "lag_7"]
    cut = int(len(daily) * 0.75)
    train = daily.iloc[:cut]
    test = daily.iloc[cut:]
    reg = RandomForestRegressor(n_estimators=240, max_depth=6, random_state=RANDOM_STATE)
    reg.fit(train[features], train["tx_count"])
    pred = reg.predict(test[features])
    mae = mean_absolute_error(test["tx_count"], pred)
    rmse = math.sqrt(mean_squared_error(test["tx_count"], pred))
    mape = mean_absolute_percentage_error(test["tx_count"], pred) * 100
    out = test[["date", "tx_count"]].copy()
    out["prediction"] = np.round(pred, 1)
    out.to_csv(OUT_DIR / "daily_forecast.csv", index=False)
    fig, ax = plt.subplots(figsize=(8.0, 4.4))
    ax.plot(pd.to_datetime(out["date"]), out["tx_count"], marker="o", label="факт")
    ax.plot(pd.to_datetime(out["date"]), out["prediction"], marker="o", label="прогноз")
    ax.set_title("Фактическое и прогнозное количество транзакций")
    ax.set_xlabel("Дата")
    ax.set_ylabel("Транзакций в день")
    ax.tick_params(axis="x", rotation=35)
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_5_daily_forecast.png", dpi=220)
    plt.close(fig)
    return {"daily": daily, "forecast": out, "mae": mae, "rmse": rmse, "mape": mape}


def logistic_coefficients(model: Pipeline, categorical: List[str], numeric: List[str]) -> pd.DataFrame:
    prep = model.named_steps["prep"]
    clf = model.named_steps["clf"]
    names = list(prep.named_transformers_["cat"].get_feature_names_out(categorical)) + numeric
    coefs = clf.coef_[0]
    out = pd.DataFrame({"feature": names, "coefficient": coefs})
    out["abs_coef"] = out["coefficient"].abs()
    out = out.sort_values("abs_coef", ascending=False).head(12)
    out.to_csv(OUT_DIR / "logistic_coefficients.csv", index=False)
    return out


def feature_importance(best_model: Pipeline, X_test: pd.DataFrame, y_test: pd.Series) -> pd.DataFrame:
    result = permutation_importance(best_model, X_test, y_test, n_repeats=8, random_state=RANDOM_STATE, scoring="f1")
    out = pd.DataFrame({"feature": X_test.columns, "importance": result.importances_mean}).sort_values("importance", ascending=False)
    out.to_csv(OUT_DIR / "feature_importance.csv", index=False)
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    top = out.head(10).iloc[::-1]
    ax.barh(top["feature"], top["importance"])
    ax.set_title("Перестановочная значимость признаков")
    ax.set_xlabel("Среднее снижение F1")
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_4_6_feature_importance.png", dpi=220)
    plt.close(fig)
    return out


def optional_shap(best_model: Pipeline, X_test: pd.DataFrame) -> str:
    # SHAP is mentioned as an optional XAI extension. For reproducible fast execution,
    # the main text uses logistic coefficients and permutation importance.
    return "SHAP оставлен как возможное расширение, основной XAI-блок построен на коэффициентах и permutation importance"


def make_architecture_diagrams() -> None:
    # Sequence diagram as a clean static figure.
    actors = ["Игрок", "Игровая\nсистема", "Агрегатор", "Резидент\nПВТ", "СККС", "ML-модуль", "Внутренний\nконтроль"]
    x = np.arange(len(actors))
    fig, ax = plt.subplots(figsize=(11.0, 6.0))
    ax.axis("off")
    for xi, label in zip(x, actors):
        ax.text(xi, 1.02, label, ha="center", va="bottom", fontsize=10, fontweight="bold", bbox=dict(boxstyle="round,pad=0.35", fc="white", ec="black"))
        ax.plot([xi, xi], [0.05, 0.95], linestyle="--", color="gray", linewidth=1)
    messages = [
        (0, 1, 0.88, "выбор способа оплаты"),
        (1, 2, 0.78, "создание заявки"),
        (2, 3, 0.68, "передача операции"),
        (3, 2, 0.58, "статус и подтверждение клиента"),
        (2, 4, 0.48, "запрос контрольной проверки"),
        (4, 2, 0.38, "подтверждение / отказ"),
        (2, 5, 0.28, "оценка вероятности риска"),
        (5, 6, 0.18, "manual_review при превышении порога"),
        (2, 1, 0.08, "зачисление или блокировка"),
    ]
    for a, b, y, label in messages:
        ax.annotate("", xy=(b, y), xytext=(a, y), arrowprops=dict(arrowstyle="->", lw=1.2))
        ax.text((a + b) / 2, y + 0.02, label, ha="center", va="bottom", fontsize=9)
    ax.set_xlim(-0.5, len(actors) - 0.5)
    ax.set_ylim(0, 1.1)
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_3_4_sequence_diagram.png", dpi=220)
    plt.close(fig)

    # ER diagram.
    entities = {
        "PLAYER": ["player_hash PK", "kyc_score", "account_age_days"],
        "PAYMENT_CHANNEL": ["channel_id PK", "channel", "commission_rate"],
        "TRANSACTION": ["transaction_id PK", "player_hash FK", "channel_id FK", "amount_byn", "timestamp", "status"],
        "ML_SCORE": ["score_id PK", "transaction_id FK", "risk_probability", "threshold", "model_version"],
        "MANUAL_REVIEW": ["review_id PK", "transaction_id FK", "reason", "decision", "review_time"],
        "DAILY_AGGREGATE": ["date PK", "tx_count", "manual_share", "crypto_share"],
    }
    positions = {
        "PLAYER": (0.05, 0.65), "PAYMENT_CHANNEL": (0.05, 0.20), "TRANSACTION": (0.39, 0.42),
        "ML_SCORE": (0.72, 0.65), "MANUAL_REVIEW": (0.72, 0.20), "DAILY_AGGREGATE": (0.39, 0.05),
    }
    fig, ax = plt.subplots(figsize=(11.0, 6.0))
    ax.axis("off")
    boxes = {}
    for ent, attrs in entities.items():
        px, py = positions[ent]
        w, h = 0.25, 0.22 if ent != "TRANSACTION" else 0.27
        rect = plt.Rectangle((px, py), w, h, fill=False, linewidth=1.2)
        ax.add_patch(rect)
        ax.text(px + w/2, py + h - 0.035, ent, ha="center", va="top", fontsize=10, fontweight="bold")
        for i, attr in enumerate(attrs):
            ax.text(px + 0.015, py + h - 0.075 - i*0.032, attr, ha="left", va="top", fontsize=8.5)
        boxes[ent] = (px, py, w, h)
    def connect(e1, e2, text):
        x1, y1, w1, h1 = boxes[e1]; x2, y2, w2, h2 = boxes[e2]
        start = (x1 + w1, y1 + h1/2); end = (x2, y2 + h2/2)
        if x1 > x2:
            start = (x1, y1 + h1/2); end = (x2 + w2, y2 + h2/2)
        ax.annotate("", xy=end, xytext=start, arrowprops=dict(arrowstyle="->", lw=1.1))
        ax.text((start[0]+end[0])/2, (start[1]+end[1])/2 + 0.02, text, ha="center", va="bottom", fontsize=8)
    connect("PLAYER", "TRANSACTION", "1:N")
    connect("PAYMENT_CHANNEL", "TRANSACTION", "1:N")
    connect("TRANSACTION", "ML_SCORE", "1:1")
    connect("TRANSACTION", "MANUAL_REVIEW", "1:0..1")
    connect("TRANSACTION", "DAILY_AGGREGATE", "N:1")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    fig.tight_layout()
    fig.savefig(OUT_DIR / "fig_3_5_er_diagram.png", dpi=220)
    plt.close(fig)


def main() -> None:
    make_architecture_diagrams()
    df = generate_transactions()
    df.to_csv(OUT_DIR / "transactions_anonymized_model.csv", index=False)
    summary = {
        "transactions": int(len(df)),
        "players": int(df["player_hash"].nunique()),
        "period": f"{df['date'].min()} – {df['date'].max()}",
        "turnover_byn": round(float(df["amount_byn"].sum()), 2),
        "median_amount_byn": round(float(df["amount_byn"].median()), 2),
        "crypto_share_pct": round(float(df["is_crypto"].mean() * 100), 2),
        "avg_latency_sec": round(float(df["latency_sec"].mean()), 1),
        "manual_review_pct": round(float(df["manual_review"].mean() * 100), 2),
        "technical_decline_pct": round(float((df["status"] == "declined").mean() * 100), 2),
    }
    pd.DataFrame([summary]).to_csv(OUT_DIR / "dataset_summary.csv", index=False)
    plot_channel_distribution(df)

    result = train_models(df)
    plot_roc(result["y_test"], result["best_proba"])
    plot_confusion(result["y_test"], result["best_pred"])
    sens = threshold_sensitivity(result["y_test"], result["best_proba"])
    q = queue_analysis(sens, result["test_df"])
    costs = cost_threshold_analysis(result["y_test"], result["best_proba"])
    forecast = train_daily_forecast(df)
    feat_imp = feature_importance(result["best_model"], result["X_test"], result["y_test"])
    coeffs = None
    if "LogisticRegression" in result["models"]:
        coeffs = logistic_coefficients(result["models"]["LogisticRegression"], result["categorical"], result["numeric"])
    shap_status = optional_shap(result["best_model"], result["X_test"])

    report = {
        "summary": summary,
        "best_model": result["best_name"],
        "best_threshold": round(float(result["best_threshold"]), 3),
        "forecast": {"mae": round(float(forecast["mae"]), 2), "rmse": round(float(forecast["rmse"]), 2), "mape_pct": round(float(forecast["mape"]), 2)},
        "cost_best_threshold": float(costs.loc[costs["cost_byn"].idxmin(), "threshold"]),
        "cost_min_byn": float(costs["cost_byn"].min()),
        "shap_status": shap_status,
    }
    with open(OUT_DIR / "experiment_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
